baseURL = "https://github.com/khanhsss0209"
languageCode = "vi"
title = "Blog Láº­p TrÃ¬nh Máº¡ng"
theme = "PaperMod"

[params]
  author = "Pháº¡m Quá»‘c KhÃ¡nh"
  description = "Chia sáº» kiáº¿n thá»©c vá» láº­p trÃ¬nh máº¡ng, Java & JavaScript"
  defaultTheme = "light"
  ShowReadingTime = true
  ShowShareButtons = true

[[menu.main]]
  name = "ğŸ  Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "ğŸ“ Blog"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "ğŸ‘¤ Giá»›i thiá»‡u"
  url = "/about/"
  weight = 3
